- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: master
  hooks:
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: debug-statements
  - id: check-added-large-files
  - id: check-ast
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-json
  - id: pretty-format-json
  - id: check-symlinks
  - id: check-yaml

- repo: git://github.com/Lucas-C/pre-commit-hooks
  sha: master
  hooks:
  - id: remove-tabs
